import {
  Project,
  Character,
  CharacterVersion,
  CharacterReference,
  GlobalStyle,
  GlobalStyleVersion,
  Season,
  Episode,
  ProviderAdapterSpec,
} from '../types';

export const SEED_PROJECT: Project = {
  id: 'proj_pikem_001',
  name: 'Pi & Kem Family Animation',
  vietnameseName: 'Hoạt Hình Gia Đình Pi & Kem',
  description:
    'A warm, hilarious, and educational recurring 3D CGI animation universe following the daily joyful adventures of Pi, Kem, their parents Ba Trường & Mẹ Vân, and puppy Mochi.',
  universe: 'Pi & Kem Animation Universe (3D CGI)',
  targetAudience: 'Preschool & Early Elementary (3–8 years) & Family Co-viewing',
  aspectRatio: '16:9 Cinematic',
  defaultLanguage: 'Vietnamese (Primary) / English (Global Dub)',
  createdAt: '2026-01-10T08:00:00.000Z',
  updatedAt: '2026-09-01T10:30:00.000Z',
};

export const SEED_GLOBAL_STYLE: GlobalStyle = {
  id: 'style_pikem_001',
  projectId: 'proj_pikem_001',
  name: 'Pi & Kem Signature 3D Cinematic Style',
  activeVersionId: 'style_ver_1_0',
  createdAt: '2026-01-10T08:00:00.000Z',
  updatedAt: '2026-01-15T09:00:00.000Z',
};

export const SEED_GLOBAL_STYLE_VERSIONS: GlobalStyleVersion[] = [
  {
    id: 'style_ver_1_0',
    styleId: 'style_pikem_001',
    version: 'v1.0',
    changeNotes: 'Initial production baseline style for Season 1 episodes.',
    animationStyle: 'High-quality cinematic 3D animated movie style, Pixar/Illumination inspired aesthetic',
    lighting: 'Warm cinematic soft studio lighting, golden hour ambient rim light, gentle indoor fill',
    colorPalette: 'Vibrant pastel colors, warm peach, sky blue, playful lemon yellow, cozy teal',
    cameraStyle: 'Eye-level child perspective, gentle slow dolly movements, cinematic focal depth',
    environmentStyle: 'Modern bright family home, child-friendly rounded furniture, soft tactile textures',
    characterRendering: 'Polished 3D stylized cartoon rendering, expressive big eyes, soft skin subsurface scattering',
    texture: 'Detailed but soft fabric weave, stylized hair strands, clean vinyl & wooden materials',
    cinematography: 'Cinematic composition, soft depth of field, balanced rule of thirds, child-safe framing',
    aspectRatio: '16:9',
    resolution: '4K UHD (3840x2160) / 1080p Master',
    fps: 24,
    targetPlatform: 'YouTube Kids, OTT Streaming, Broadcast Television',
    globalPrompt:
      'High-quality cinematic 3D animated movie style, polished 3D rendering, warm cinematic lighting, vibrant pastel colors, expressive child-friendly characters, detailed but soft environments, modern family home, cinematic composition, soft depth of field, colorful children animation.',
    negativePrompt:
      'wrong character identity, inconsistent face, inconsistent hairstyle, inconsistent clothing, incorrect age, adult proportions, distorted anatomy, extra fingers, missing fingers, extra limbs, duplicated characters, deformed face, unnatural eyes, incorrect number of characters, duplicate person, cropped character, broken hands, malformed body, text, watermark, logo, blurry, low quality',
    status: 'Active',
    createdAt: '2026-01-10T08:00:00.000Z',
  },
  {
    id: 'style_ver_1_1',
    styleId: 'style_pikem_001',
    version: 'v1.1',
    changeNotes: 'Enhanced outdoor sunshine lighting and saturated lawn greenery for picnic episodes.',
    animationStyle: 'High-quality cinematic 3D animated movie style, enhanced subsurface scattering',
    lighting: 'Vivid morning sunlight with soft volumetric light rays and delicate rim highlights',
    colorPalette: 'Fresh grassy green, radiant morning yellow, sky pastel cyan, blossom coral',
    cameraStyle: 'Wide family master shots, low-angle dynamic child running tracking shots',
    environmentStyle: 'Sunny outdoor backyard garden, lush green lawn, wooden patio deck, colorful flowerbeds',
    characterRendering: 'Ultra-crisp 3D stylized models with high micro-contrast and expressive facial shapes',
    texture: 'Soft denim fiber, cotton knit, puppy fluffy fur grooming, water droplet reflections',
    cinematography: 'Dynamic cinematic framing, gentle motion blur, rich bokeh depth of field',
    aspectRatio: '16:9',
    resolution: '4K UHD (3840x2160)',
    fps: 24,
    targetPlatform: 'YouTube Kids & Cinema Festivals',
    globalPrompt:
      'High-quality cinematic 3D animated movie style, polished 3D rendering, radiant outdoor morning sunlight, lush lawn, vibrant pastel colors, expressive child-friendly characters, rich bokeh, colorful family animation.',
    negativePrompt:
      'wrong character identity, inconsistent face, inconsistent hairstyle, inconsistent clothing, incorrect age, adult proportions, distorted anatomy, extra fingers, missing fingers, extra limbs, duplicated characters, deformed face, unnatural eyes, incorrect number of characters, duplicate person, cropped character, broken hands, malformed body, text, watermark, logo, blurry, low quality',
    status: 'Draft',
    createdAt: '2026-02-14T11:00:00.000Z',
  },
];

export const SEED_CHARACTERS: Character[] = [
  {
    id: 'char_ethan',
    projectId: 'proj_pikem_001',
    displayName: 'Ethan (Ba Trường)',
    englishName: 'Ethan',
    vietnameseName: 'Ba Trường',
    role: 'Father',
    isSupporting: false,
    activeVersionId: 'ver_ethan_v1',
    colorScheme: {
      primary: '#2563eb', // royal blue
      secondary: '#38bdf8',
      accent: '#f59e0b',
      bgGradients: 'from-blue-600 to-indigo-800',
    },
    createdAt: '2026-01-10T08:30:00.000Z',
    updatedAt: '2026-01-10T08:30:00.000Z',
  },
  {
    id: 'char_emma',
    projectId: 'proj_pikem_001',
    displayName: 'Emma (Mẹ Vân)',
    englishName: 'Emma',
    vietnameseName: 'Mẹ Vân',
    role: 'Mother',
    isSupporting: false,
    activeVersionId: 'ver_emma_v1',
    colorScheme: {
      primary: '#ec4899', // rose pink
      secondary: '#f472b6',
      accent: '#8b5cf6',
      bgGradients: 'from-rose-500 to-purple-700',
    },
    createdAt: '2026-01-10T08:35:00.000Z',
    updatedAt: '2026-01-10T08:35:00.000Z',
  },
  {
    id: 'char_pi',
    projectId: 'proj_pikem_001',
    displayName: 'Pi (Nancy)',
    englishName: 'Nancy',
    vietnameseName: 'Pi',
    role: 'Older sister',
    isSupporting: false,
    activeVersionId: 'ver_pi_v1',
    colorScheme: {
      primary: '#f97316', // bright orange / coral
      secondary: '#fb923c',
      accent: '#ec4899',
      bgGradients: 'from-amber-500 to-pink-600',
    },
    createdAt: '2026-01-10T08:40:00.000Z',
    updatedAt: '2026-01-10T08:40:00.000Z',
  },
  {
    id: 'char_kem',
    projectId: 'proj_pikem_001',
    displayName: 'Kem (Leo)',
    englishName: 'Leo',
    vietnameseName: 'Kem',
    role: 'Younger brother',
    isSupporting: false,
    activeVersionId: 'ver_kem_v1',
    colorScheme: {
      primary: '#10b981', // emerald mint green
      secondary: '#34d399',
      accent: '#facc15',
      bgGradients: 'from-emerald-500 to-teal-700',
    },
    createdAt: '2026-01-10T08:45:00.000Z',
    updatedAt: '2026-01-10T08:45:00.000Z',
  },
  {
    id: 'char_mochi',
    projectId: 'proj_pikem_001',
    displayName: 'Mochi (Cún Mochi)',
    englishName: 'Mochi',
    vietnameseName: 'Cún Mochi',
    role: 'Permanent supporting character',
    isSupporting: true,
    activeVersionId: 'ver_mochi_v1',
    colorScheme: {
      primary: '#eab308', // warm butter yellow
      secondary: '#fef08a',
      accent: '#d97706',
      bgGradients: 'from-amber-400 to-yellow-600',
    },
    createdAt: '2026-01-10T08:50:00.000Z',
    updatedAt: '2026-01-10T08:50:00.000Z',
  },
];

export const SEED_CHARACTER_VERSIONS: CharacterVersion[] = [
  // Ethan v1
  {
    id: 'ver_ethan_v1',
    characterId: 'char_ethan',
    version: 'v1.0',
    changeNotes: 'Initial production DNA for Ba Trường (Ethan). Casual home & work outfit.',
    age: '33 years old',
    gender: 'Male',
    height: '178 cm (tall, protective dad build)',
    bodyProportions: 'Athletic yet comfortable dad silhouette, slightly broad shoulders, approachable posture',
    faceShape: 'Gently rounded square jaw with warm smiling cheeks, clean-shaven, light laugh lines around eyes',
    skinTone: 'Healthy light golden Vietnamese skin tone, warm undertone',
    hair: 'Short neat modern dark brown hair, slight stylish side taper, clean and well-kept',
    eyes: 'Warm almond-shaped dark hazel eyes, gentle eyebrows, expressive and patient expression',
    nose: 'Straight friendly nose with soft rounded tip',
    mouth: 'Comfortable natural smile, clean teeth, friendly laughing mouth shape',
    facialExpression: 'Good-humored, attentive, affectionate fatherly gaze with a slight playful twinkle',
    clothing: 'Navy blue polo shirt with faint cyan trim collar, comfortable khaki chino pants rolled neatly at ankles',
    shoes: 'Clean white minimalist leather sneakers with navy heel accents',
    accessories: 'Smart digital fitness wristband on left wrist, occasional sleek wireframe reading glasses when coding',
    personality: 'Funny, caring, highly responsible, humorous storyteller, patient teacher',
    behavior: 'Loves inventing playful bedtime games, mimics funny sound effects when playing with Pi & Kem, checks on everyone thoughtfully',
    voiceDescription: 'Warm, reassuring baritone voice with a friendly melodic cadence, gentle comedic pauses',
    typicalEmotions: 'Fond amusement, proud paternal joy, calm encouragement, mock surrender when kids gang up on him',
    typicalGestures: 'Playfully tapping kids on their nose, lifting Kem onto his shoulders, clapping enthusiastically',
    relationships: 'Loving husband to Emma (Mẹ Vân); deeply adored and trusted dad to Pi and Kem; patient protector of Mochi',
    visualKeywords: [
      '3D stylized animated father',
      'programmer dad',
      'navy polo shirt',
      'khaki pants',
      'short dark brown hair',
      'warm hazel eyes',
      'friendly smile',
      'clean 3D render',
    ],
    characterPrompt:
      '3D CGI stylized animation of Ethan (Ba Trường), a 33-year-old Vietnamese father, programmer, athletic comfortable build, short stylish dark brown hair, warm hazel eyes, friendly smile, navy blue polo shirt, khaki chinos, clean white sneakers, warm lighting, Pixar-quality animation aesthetic.',
    negativePrompt:
      'distorted proportions, exaggerated muscles, wrinkled elder face, frown, scowl, formal suit, tie, blurry render, photographic realistic skin, extra limbs, watermark',
    status: 'Active',
    createdAt: '2026-01-10T08:30:00.000Z',
  },

  // Emma v1
  {
    id: 'ver_emma_v1',
    characterId: 'char_emma',
    version: 'v1.0',
    changeNotes: 'Initial production DNA for Mẹ Vân (Emma). Vibrant casual mother outfit.',
    age: '31 years old',
    gender: 'Female',
    height: '164 cm (graceful, energetic mother silhouette)',
    bodyProportions: 'Slender, balanced feminine posture, warm and welcoming body language',
    faceShape: 'Soft oval face with gentle cheekbones, bright youthful complexion',
    skinTone: 'Fair rosy-warm Asian skin tone, natural soft glow',
    hair: 'Glossy shoulder-length wavy chestnut brown hair, often tied in a chic low half-ponytail with pastel hair ribbon',
    eyes: 'Large expressive dark brown almond eyes, soft feminine lashes, sparkling with intelligence and love',
    nose: 'Delicate straight nose with subtle contour',
    mouth: 'Sweet petal lips with light coral tint, radiant warm smile',
    facialExpression: 'Encouraging, empathetic, joyful, lovingly observant',
    clothing: 'Soft coral-pink ribbed knit cardigan over a cream linen short-sleeve top, comfortable high-waist seafoam pants',
    shoes: 'Beige slip-on canvas espadrilles with tiny pastel embroidery',
    accessories: 'Delicate gold teardrop pendant necklace, small pearl stud earrings, pastel scrunchie on wrist',
    personality: 'Warm, highly intelligent, nurturing, organized yet playful, loves travelling and discovery',
    behavior: 'Always prepares creative craft activities, gently mediates sibling squabbles with humor, loves capturing family moments',
    voiceDescription: 'Clear, musical, gentle soprano with soothing maternal clarity and cheerful upbeat notes',
    typicalEmotions: 'Tender affection, delight in children creativity, empathetic listening, joyful laughter',
    typicalGestures: 'Gently tucking hair behind her ear, spreading out craft mats, kneeling down to child eye level',
    relationships: 'Devoted partner to Ethan; loving mother, mentor and best friend to Pi and Kem; spoils Mochi with healthy treats',
    visualKeywords: [
      '3D stylized animated mother',
      'career consultant mom',
      'coral cardigan',
      'wavy chestnut hair',
      'pearl earrings',
      'warm bright eyes',
      'loving smile',
      'cinematic children animation',
    ],
    characterPrompt:
      '3D CGI stylized animation of Emma (Mẹ Vân), a 31-year-old Vietnamese mother, career consultant, graceful slender build, wavy shoulder-length chestnut brown hair, large expressive dark eyes, coral-pink cardigan over cream top, pastel pants, gentle warm smile, family animation style.',
    negativePrompt:
      'harsh makeup, angular severe face, sad expression, messy clothing, unrealistic body shape, elderly wrinkles, gothic, dark gloomy lighting, extra fingers, watermark',
    status: 'Active',
    createdAt: '2026-01-10T08:35:00.000Z',
  },

  // Pi v1
  {
    id: 'ver_pi_v1',
    characterId: 'char_pi',
    version: 'v1.0',
    changeNotes: 'Initial production DNA for Pi (Nancy) - Main protagonist older sister.',
    age: '6 years old (approx 5-7 years)',
    gender: 'Female',
    height: '112 cm (energetic kindergarten proportions)',
    bodyProportions: 'Cute 3.5 heads tall stylized child proportions, bouncy posture, light and quick movements',
    faceShape: 'Chubby round cheeks, button chin, cute expressive face that lights up instantly',
    skinTone: 'Warm peachy sun-kissed child skin tone, soft rosy cheeks',
    hair: 'Playful jet-black hair styled into two bouncing high pigtails fastened with cheerful yellow star clips, wispy bangs',
    eyes: 'Very large sparkling black eyes with star-like reflections, wide open with wonder, expressive curved eyebrows',
    nose: 'Tiny cute button nose',
    mouth: 'Expressive wide smile showing small baby teeth, adorable giggle shape',
    facialExpression: 'Bursting with curiosity, adventurous determination, infectious joy',
    clothing: 'Bright sunny-yellow sleeveless cotton dress with a cute embroidered dancing rainbow patch, over a striped peach tee',
    shoes: 'Lightweight cherry-red sneaker-boots with flexible white rubber soles, colorful mismatched socks',
    accessories: 'Pair of yellow star hairpins, small teal canvas crossbody pouch containing crayons and tiny treasures',
    personality: 'Energetic, relentlessly curious, playful, adventurous, spontaneous dancer, protective big sister',
    behavior: 'Breaks into spontaneous happy dance steps when excited, leads explorations around the house, teaches Kem new discoveries',
    voiceDescription: 'Bright, bouncy, high-pitched melodic child voice with animated pitch jumps when inspired',
    typicalEmotions: 'Awe-struck wonder, boundless enthusiasm, competitive eagerness, sudden tender concern for Kem',
    typicalGestures: 'Spinning on one foot, pointing enthusiastically at bugs or paintings, grabbing Kem hand to run',
    relationships: 'Daughter of Ethan & Emma; adored idol and leader to younger brother Kem; partner-in-crime with puppy Mochi',
    visualKeywords: [
      '3D animated girl',
      '6-year-old child protagonist',
      'twin pigtails with star clips',
      'yellow summer dress',
      'cherry red sneakers',
      'sparkling big eyes',
      'dancing child',
      '3D children series',
    ],
    characterPrompt:
      '3D CGI stylized animation of Pi (Nancy), 6-year-old Vietnamese girl, cute 3.5 heads child proportion, twin bouncy pigtails with yellow star hair clips, large sparkling black eyes, bright sunny yellow dress with rainbow patch, cherry red sneakers, joyful dancing pose, Pixar/Illumination animation aesthetic.',
    negativePrompt:
      'adult proportions, teenager appearance, sad face, distorted hands, creepy eyes, realism uncanny valley, dull colors, dark lighting, extra limbs, watermark',
    status: 'Active',
    createdAt: '2026-01-10T08:40:00.000Z',
  },

  // Kem v1
  {
    id: 'ver_kem_v1',
    characterId: 'char_kem',
    version: 'v1.0',
    changeNotes: 'Initial production DNA for Kem (Leo) - Adorable mischievous toddler younger brother.',
    age: '3.5 years old (approx 3-4 years)',
    gender: 'Male',
    height: '92 cm (toddler silhouette, adorable waddling gait)',
    bodyProportions: 'Cute 2.8 heads tall stylized toddler proportions, chubby round tummy, cute baby wrist rolls',
    faceShape: 'Super chubby baby cheeks like freshly steamed dumplings, button chin, dimple on right cheek',
    skinTone: 'Creamy soft toddler skin tone with natural healthy blush on cheeks and nose tip',
    hair: 'Fluffy soft dark hair with a cute mischievous cowlick tuft standing proudly at the crown',
    eyes: 'Huge round dewy puppy eyes, long cute lashes, wide with innocent curiosity that hides funny mischief',
    nose: 'Adorable tiny button nose',
    mouth: 'Cupid bow baby lips, tiny toothy grin, funny pout when pretending to concentrate',
    facialExpression: 'Sweet innocence with a cheeky mischievous twinkle, hilarious amazed gasps',
    clothing: 'Soft mint-green denim dungaree overalls over a pale-lemon short-sleeved bodysuit with a friendly baby dinosaur print',
    shoes: 'Chubby baby trainers in vibrant turquoise blue with squeaky soles and velcro straps',
    accessories: 'Cute dinosaur tail patch on back of overalls, soft silicone dinosaur wrist teether toy',
    personality: 'Irresistibly cute, intensely curious, playful, mischievous mimic, affectionate shadow',
    behavior: 'Follows Pi everywhere like her personal apprentice, copies her dancing with clumsy toddler hops, creates funny accidental chaos',
    voiceDescription: 'Charming toddler voice with adorable half-words, enthusiastic giggles, funny squeaks when surprised',
    typicalEmotions: 'Pure wide-eyed fascination, silly pride after copying Pi, funny drama-pout when denied a snack, instant giggles',
    typicalGestures: 'Clumsy two-footed jumps, clapping his chubby hands, hiding behind Pi legs, hugging Mochi like a teddy bear',
    relationships: 'Youngest son of Ethan & Emma; completely idolizes big sister Pi; best cuddle buddy to puppy Mochi',
    visualKeywords: [
      '3D animated toddler boy',
      '3-year-old child character',
      'mint green overalls dungarees',
      'fluffy hair with cowlick',
      'huge curious eyes',
      'chubby dumpling cheeks',
      'cute toddler',
      '3D children series',
    ],
    characterPrompt:
      '3D CGI stylized animation of Kem (Leo), 3-year-old toddler boy, cute 2.8 heads proportion, chubby dumpling cheeks, fluffy dark hair with cute cowlick tuft, mint green dungaree overalls over pale yellow tee, turquoise baby sneakers, mischievous innocent expression, high-end 3D animated series.',
    negativePrompt:
      'older child, adult proportions, skinny face, aggressive look, sad tears, complex adult clothing, realistic skin pores, low poly, extra limbs, watermark',
    status: 'Active',
    createdAt: '2026-01-10T08:45:00.000Z',
  },

  // Mochi v1
  {
    id: 'ver_mochi_v1',
    characterId: 'char_mochi',
    version: 'v1.0',
    changeNotes: 'Initial production DNA for Mochi the permanent family puppy.',
    age: '8 months old (puppy stage)',
    gender: 'Male',
    height: '28 cm shoulder height (small lap puppy)',
    bodyProportions: 'Fluffy cloud-like rounded puppy silhouette, short stumpy legs, delightfully wiggly tail',
    faceShape: 'Round fluffy teddy bear face with soft plush muzzle',
    skinTone: 'Creamy ivory and biscuit-tinted puppy coat',
    hair: 'Ultra-soft fluffy cream-colored puppy fur with warm marshmallow hues, velvety soft texture',
    eyes: 'Large glossy obsidian-black expressive puppy eyes with warm liquid highlights',
    nose: 'Shiny wet black button nose, constantly twitching with curiosity',
    mouth: 'Gentle happy dog grin, soft pink tongue lolling out when panting joyfully',
    facialExpression: 'Extremely sweet, eager, playful, slightly bewildered by toddler games',
    clothing: 'No clothing; wears a custom comfortable cherry-red woven puppy collar with a shiny golden bell and bone tag',
    shoes: 'Four tiny cream-colored paws with soft pink toe-beans',
    accessories: 'Shiny gold bone-shaped name tag engraved with "Mochi"',
    personality: 'Cute, energetic, loyal, playful, food-motivated, enthusiastic accomplice to children games',
    behavior: 'Chases bouncing balls, tilts head inquisitively at strange noises, curls up at Pi feet when she draws',
    voiceDescription: 'Cute squeaky puppy yips, joyful tail-thump rhythm, soft sleepy sighs',
    typicalEmotions: 'Unconditional puppy devotion, boundless excitement when someone says "walk" or "paint", comically startled by bubbles',
    typicalGestures: 'Tilting head 45 degrees, vigorous tail wagging that shakes his whole backside, pawing gently for cuddles',
    relationships: 'Beloved pet to all family members; Pi dance partner; Kem snuggle pillow; Ba Trường running buddy',
    visualKeywords: [
      '3D animated puppy',
      'cream fluffy puppy',
      'floppy ears',
      'shiny black eyes',
      'red collar with gold bell',
      'teddy bear dog',
      'cute animal character',
      '3D children animation',
    ],
    characterPrompt:
      '3D CGI stylized animation of Mochi, small fluffy cream-colored puppy, floppy ears, large glossy black expressive eyes, wet button nose, red collar with gold bell tag, adorable playful pose, Pixar style fur rendering, warm cinematic studio lighting.',
    negativePrompt:
      'ferocious dog, realistic wolf, mangy fur, flat 2D cartoon, distorted paws, extra tail, unnatural colors, robotic, watermark',
    status: 'Active',
    createdAt: '2026-01-10T08:50:00.000Z',
  },
];

export const SEED_CHARACTER_REFERENCES: CharacterReference[] = [
  // Pi References
  {
    id: 'ref_pi_front',
    characterId: 'char_pi',
    characterVersionId: 'ver_pi_v1',
    type: 'Front',
    image: 'pi_front',
    thumbnail: 'pi_front_thumb',
    description: 'Orthographic front turn: Full body neutral stance with yellow dress and star clips.',
    active: true,
    createdAt: '2026-01-10T09:00:00.000Z',
  },
  {
    id: 'ref_pi_34',
    characterId: 'char_pi',
    characterVersionId: 'ver_pi_v1',
    type: '3/4',
    image: 'pi_34',
    thumbnail: 'pi_34_thumb',
    description: '3/4 beauty shot: Showing facial volume, ponytail silhouette, and smiling eyes.',
    active: true,
    createdAt: '2026-01-10T09:05:00.000Z',
  },
  {
    id: 'ref_pi_side',
    characterId: 'char_pi',
    characterVersionId: 'ver_pi_v1',
    type: 'Side',
    image: 'pi_side',
    thumbnail: 'pi_side_thumb',
    description: 'Side profile turn: Demonstrates nose angle, pigtail attachment point, and shoe curvature.',
    active: true,
    createdAt: '2026-01-10T09:10:00.000Z',
  },
  {
    id: 'ref_pi_expression',
    characterId: 'char_pi',
    characterVersionId: 'ver_pi_v1',
    type: 'Expression',
    image: 'pi_expression',
    thumbnail: 'pi_expression_thumb',
    description: 'Key emotional sheet: Laughing, curious wonder, determined explorer, and sweet sibling hug.',
    active: true,
    createdAt: '2026-01-10T09:15:00.000Z',
  },
  {
    id: 'ref_pi_clothing',
    characterId: 'char_pi',
    characterVersionId: 'ver_pi_v1',
    type: 'Clothing',
    image: 'pi_clothing',
    thumbnail: 'pi_clothing_thumb',
    description: 'Costume turnaround: Stitching details on rainbow patch, pocket seam, and cherry sneakers.',
    active: true,
    createdAt: '2026-01-10T09:20:00.000Z',
  },
  {
    id: 'ref_pi_pose',
    characterId: 'char_pi',
    characterVersionId: 'ver_pi_v1',
    type: 'Pose',
    image: 'pi_pose',
    thumbnail: 'pi_pose_thumb',
    description: 'Action dynamic poses: Spontaneous twist dance, holding paintbrush, running forward.',
    active: true,
    createdAt: '2026-01-10T09:25:00.000Z',
  },

  // Kem References
  {
    id: 'ref_kem_front',
    characterId: 'char_kem',
    characterVersionId: 'ver_kem_v1',
    type: 'Front',
    image: 'kem_front',
    thumbnail: 'kem_front_thumb',
    description: 'Orthographic front turn: Mint dungarees, cowlick tuft, and chubby cheeks.',
    active: true,
    createdAt: '2026-01-10T09:30:00.000Z',
  },
  {
    id: 'ref_kem_34',
    characterId: 'char_kem',
    characterVersionId: 'ver_kem_v1',
    type: '3/4',
    image: 'kem_34',
    thumbnail: 'kem_34_thumb',
    description: '3/4 beauty view: Cheeky toddler grin, dinosaur patch on dungaree bib.',
    active: true,
    createdAt: '2026-01-10T09:35:00.000Z',
  },
  {
    id: 'ref_kem_side',
    characterId: 'char_kem',
    characterVersionId: 'ver_kem_v1',
    type: 'Side',
    image: 'kem_side',
    thumbnail: 'kem_side_thumb',
    description: 'Side profile turn: Round toddler belly contour, dinosaur tail patch behind.',
    active: true,
    createdAt: '2026-01-10T09:40:00.000Z',
  },
  {
    id: 'ref_kem_expression',
    characterId: 'char_kem',
    characterVersionId: 'ver_kem_v1',
    type: 'Expression',
    image: 'kem_expression',
    thumbnail: 'kem_expression_thumb',
    description: 'Expression sheet: Toddler giggles, funny innocent pout, wide-eyed awe.',
    active: true,
    createdAt: '2026-01-10T09:45:00.000Z',
  },

  // Ethan References
  {
    id: 'ref_ethan_front',
    characterId: 'char_ethan',
    characterVersionId: 'ver_ethan_v1',
    type: 'Front',
    image: 'ethan_front',
    thumbnail: 'ethan_front_thumb',
    description: 'Orthographic front turn: Ba Trường in navy polo shirt and chinos.',
    active: true,
    createdAt: '2026-01-10T09:50:00.000Z',
  },
  {
    id: 'ref_ethan_34',
    characterId: 'char_ethan',
    characterVersionId: 'ver_ethan_v1',
    type: '3/4',
    image: 'ethan_34',
    thumbnail: 'ethan_34_thumb',
    description: '3/4 view: Warm smiling programmer father, approachable posture.',
    active: true,
    createdAt: '2026-01-10T09:55:00.000Z',
  },

  // Emma References
  {
    id: 'ref_emma_front',
    characterId: 'char_emma',
    characterVersionId: 'ver_emma_v1',
    type: 'Front',
    image: 'emma_front',
    thumbnail: 'emma_front_thumb',
    description: 'Orthographic front turn: Mẹ Vân in coral cardigan and soft pastel pants.',
    active: true,
    createdAt: '2026-01-10T10:00:00.000Z',
  },
  {
    id: 'ref_emma_34',
    characterId: 'char_emma',
    characterVersionId: 'ver_emma_v1',
    type: '3/4',
    image: 'emma_34',
    thumbnail: 'emma_34_thumb',
    description: '3/4 beauty view: Gentle loving mother smile, wavy chestnut hair.',
    active: true,
    createdAt: '2026-01-10T10:05:00.000Z',
  },

  // Mochi References
  {
    id: 'ref_mochi_front',
    characterId: 'char_mochi',
    characterVersionId: 'ver_mochi_v1',
    type: 'Full Body',
    image: 'mochi_front',
    thumbnail: 'mochi_front_thumb',
    description: 'Full body puppy: Fluffy cream fur, red collar with gold bell, shiny eyes.',
    active: true,
    createdAt: '2026-01-10T10:10:00.000Z',
  },
  {
    id: 'ref_mochi_expression',
    characterId: 'char_mochi',
    characterVersionId: 'ver_mochi_v1',
    type: 'Expression',
    image: 'mochi_expression',
    thumbnail: 'mochi_expression_thumb',
    description: 'Expression sheet: Head tilt, happy panting dog smile, playful pounce.',
    active: true,
    createdAt: '2026-01-10T10:15:00.000Z',
  },
];

export const SEED_SEASONS: Season[] = [
  {
    id: 'season_001',
    projectId: 'proj_pikem_001',
    seasonNumber: 1,
    title: 'Season 1: Joyful Daily Discoveries',
    vietnameseTitle: 'Mùa 1: Những Khám Phá Nhỏ Diệu Kỳ',
    description:
      'The inaugural 12-episode season focusing on everyday family milestones, creative play at home, sibling empathy, and healthy habits.',
    theme: 'Family Warmth, Creativity, Sibling Cooperation, and Emotional Growth',
    audience: 'Children 3–8 & Family Co-viewing',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    episodeCount: 12,
    styleVersionId: 'style_ver_1_0',
    seasonCharacters: ['char_pi', 'char_kem', 'char_ethan', 'char_emma', 'char_mochi'],
    notes:
      'Season 1 strictly anchors Character DNA v1 across all episodes to guarantee brand consistency and visual recognition on streaming channels.',
    status: 'In Production',
    createdAt: '2026-01-10T10:00:00.000Z',
    updatedAt: '2026-02-01T12:00:00.000Z',
  },
];

export const SEED_EPISODES: Episode[] = [
  {
    id: 'ep_009',
    seasonId: 'season_001',
    episodeNumber: 9,
    title: 'Tập 9 – Cùng nhau vẽ tranh',
    storyIdea: 'Mẹ trải một tấm bạt lớn giữa nhà để Pi và Kem cùng vẽ tranh màu nước.',
    theme: 'Sáng tạo & Chia sẻ nghệ thuật (Creativity & Sibling Bond)',
    educationalMessage:
      'Khuyến khích trẻ em tự do biểu đạt cảm xúc qua hội họa, trân trọng nét vẽ của nhau, và cùng dọn dẹp sau khi chơi.',
    characterIds: ['char_pi', 'char_kem', 'char_emma', 'char_ethan'],
    supportingCharacterIds: ['char_mochi'],
    location: 'Phòng khách gia đình ấm cúng (Living Room Canvas Area)',
    duration: '07:30 (Minutes)',
    targetPlatform: 'YouTube Kids & OTT Streaming',
    status: 'Draft',
    // HISTORICAL SNAPSHOT RULE:
    // Episode 9 explicitly locks the exact versions of characters and style!
    characterVersionSnapshots: {
      char_pi: 'ver_pi_v1',
      char_kem: 'ver_kem_v1',
      char_emma: 'ver_emma_v1',
      char_ethan: 'ver_ethan_v1',
      char_mochi: 'ver_mochi_v1',
    },
    styleVersionSnapshotId: 'style_ver_1_0',
    createdAt: '2026-02-10T09:00:00.000Z',
    updatedAt: '2026-02-15T15:30:00.000Z',
  },
];

export const SEED_PROVIDER_ADAPTERS: ProviderAdapterSpec[] = [
  {
    id: 'provider_google_flow',
    name: 'Google Flow Video Studio',
    category: 'Video Generation',
    status: 'Architecture Ready',
    description:
      'Next-generation frame-to-frame consistent camera motion and character preservation pipeline. Ready for adapter mounting.',
    supportedRatios: ['16:9', '9:16', '1:1'],
    maxDurationSeconds: 15,
    promptSyntaxPattern:
      '{GlobalStyleVersion} + [CharacterVersion.visualKeywords] + {SceneAction} + --preserve-dna {CharacterId}',
    dnaIndependenceGuarantee:
      'Guarantees 100% decoupling: Provider adapter only consumes frozen Character DNA snapshot without altering studio state.',
  },
  {
    id: 'provider_veo_api',
    name: 'Google Veo Video API',
    category: 'Video Generation',
    status: 'Architecture Ready',
    description:
      'High-fidelity cinematic 1080p/4K video generation with exceptional fluid physics and lighting fidelity.',
    supportedRatios: ['16:9', '9:16'],
    maxDurationSeconds: 8,
    promptSyntaxPattern:
      'Cinematic 3D animation, {GlobalStylePrompt}, character: {CharacterDNA.prompt}, scene: {Action}',
    dnaIndependenceGuarantee:
      'Provider changes cannot overwrite historical creative versions or episode records.',
  },
  {
    id: 'provider_runway',
    name: 'Runway Gen-3 Alpha',
    category: 'Video Generation',
    status: 'Architecture Ready',
    description:
      'Advanced camera control with structured keyframe interpolation for dynamic animation action sequences.',
    supportedRatios: ['16:9', '9:16', '4:3', '21:9'],
    maxDurationSeconds: 10,
    promptSyntaxPattern:
      '[Camera: {cameraStyle}] [Lighting: {lighting}] {Action} [Character: {visualKeywords}]',
    dnaIndependenceGuarantee:
      'Full abstraction layer isolates Runway prompt schemas from persistent Character DNA.',
  },
  {
    id: 'provider_luma',
    name: 'Luma Dream Machine',
    category: 'Video Generation',
    status: 'Architecture Ready',
    description:
      'Fast responsive volumetric physical interaction simulator, excellent for soft fabric and fluid paint splashes.',
    supportedRatios: ['16:9', '9:16', '1:1'],
    maxDurationSeconds: 5,
    promptSyntaxPattern:
      '{Action}, highly detailed 3D animated feature film, {GlobalStyle.characterRendering}',
    dnaIndependenceGuarantee:
      'Immutable character snapshots are translated strictly during job compilation.',
  },
  {
    id: 'provider_kling',
    name: 'Kling 1.5 Video Adapter',
    category: 'Video Generation',
    status: 'Architecture Ready',
    description:
      'High-motion character agility with precise facial expression maintenance for energetic children dancing.',
    supportedRatios: ['16:9', '9:16', '1:1'],
    maxDurationSeconds: 10,
    promptSyntaxPattern:
      '3D animation style, {CharacterVersion.facialExpression}, {Action}, {GlobalStyle.lighting}',
    dnaIndependenceGuarantee:
      'Multi-reference adapter compiles image URLs from CharacterReference registry without mutating core entities.',
  },
];
